### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by alex88100** [codingplc/plc-simulator#7]
Hi
I'm a "new" teacher (63 years old !) in PLC programming in Ladder.
I'm testing a lot of different method to translate grafcet in Ladder language and sometimes I've a doubt if all the condition of grafcet execution are correct. 
In the same cycle only one step can be activated .
So my request is : Is it possible to launch the execution step by step  to see what happend at every cycle ?
 I need it to explain correctly to the student,  using samples, how work a PLC

Thanks in advance
Best regards

Thierry ALEXANDRE

**Comment by dagryl** [comment]
H Alex,

Unfortunately, it is not possible to execute the code step by step at the moment. However, I can see the value in such a feature, and I may consider implementing it in the future.

**Comment by dagryl** [comment]
https://github.com/codingplc/plc-simulator/issues/2

**Comment by dagryl** [comment]
Closed as this was mentioned [here](https://github.com/codingplc/plc-simulator/issues/2)
